# Generated by Django 2.2.24 on 2022-04-23 14:05

from django.db import migrations

import phonenumbers


def validate_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats:
        validate_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(validate_number):
            flat.owner_pure_phone = validate_number
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20220423_1435'),
    ]

    operations = [
        migrations.RunPython(validate_number)
    ]
