# Generated by Django 2.2.24 on 2022-05-12 21:51

from django.db import migrations


def create_relations(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    owners = Owner.objects.all()
    for owner in owners.iterator():
        flats = Flat.objects.filter(owner=owner.owner_name)
        owner.flats.set(flats)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20220423_1948'),
    ]

    operations = [
        migrations.RunPython(create_relations)
    ]
