# Generated by Django 2.2.24 on 2022-05-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20220512_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(db_index=True, related_name='flat_owner', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
